const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94782033975"
const SESSION_ID = "PRABATH-MD~3PRVgJbA#L_wtdiMDNNsbo2Tdz1JVo5sidusOLEQjq4AcKL-D614"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
